const fileInput=document.querySelector('#fileInput'),video=document.querySelector('#video'),placeholder=document.querySelector('#placeholder'),headline=document.querySelector('#headline'),headlinePreview=document.querySelector('#headlinePreview'),toast=document.querySelector('#toast'),category=document.querySelector('#category'),categoryPreview=document.querySelector('#categoryPreview'),exportButton=document.querySelector('#exportButton');
fileInput.addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;video.src=URL.createObjectURL(file);video.style.display='block';placeholder.style.display='none';showToast(`${file.name} added to your story`)});
headline.addEventListener('input',e=>headlinePreview.textContent=e.target.value||'Your headline appears here');
category.addEventListener('change',e=>categoryPreview.textContent=e.target.value.toUpperCase());
document.querySelectorAll('.tabs button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.tabs button').forEach(b=>b.classList.remove('selected'));document.querySelectorAll('.panel').forEach(p=>p.classList.add('hidden'));button.classList.add('selected');document.querySelector(`#${button.dataset.tab}`).classList.remove('hidden')}));
document.querySelectorAll('.style').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.style').forEach(b=>b.classList.remove('selected'));button.classList.add('selected');document.documentElement.style.setProperty('--red',button.classList.contains('blue')?'#385b95':button.classList.contains('dark')?'#1d283b':'#e73d36')}));
document.querySelector('#logoToggle').addEventListener('change',e=>document.querySelector('#screenLogo').style.display=e.target.checked?'block':'none');document.querySelector('#tickerToggle').addEventListener('change',e=>document.querySelector('#ticker').style.display=e.target.checked?'block':'none');
document.querySelector('#uploadOpen').addEventListener('click',()=>{document.querySelector('#studio').scrollIntoView();fileInput.click()});document.querySelector('#newStory').addEventListener('click',()=>{document.querySelector('#studio').scrollIntoView();showToast('New story workspace opened')});
exportButton.addEventListener('click',exportEditedVideo);
async function exportEditedVideo(){
  if(!video.src){showToast('Pehle ek video upload karein');return}
  if(!window.MediaRecorder||!HTMLCanvasElement.prototype.captureStream){showToast('Please use Chrome or Edge to download video');return}
  exportButton.disabled=true;exportButton.textContent='Preparing video…';
  const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');canvas.width=1280;canvas.height=720;
  const stream=canvas.captureStream(30),chunks=[];let audioContext,destination;
  try{audioContext=new AudioContext();const source=audioContext.createMediaElementSource(video);destination=audioContext.createMediaStreamDestination();source.connect(destination);source.connect(audioContext.destination);destination.stream.getAudioTracks().forEach(track=>stream.addTrack(track));await audioContext.resume()}catch(e){}
  const recorder=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported('video/webm;codecs=vp9,opus')?'video/webm;codecs=vp9,opus':'video/webm'});
  recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.onstop=()=>{const link=document.createElement('a');link.href=URL.createObjectURL(new Blob(chunks,{type:'video/webm'}));link.download='aaj-tak-abhi-tak-edited.webm';link.click();URL.revokeObjectURL(link.href);exportButton.disabled=false;exportButton.textContent='Download edited video';showToast('Edited video downloaded')};
  const draw=()=>{if(video.paused||video.ended)return;ctx.drawImage(video,0,0,1280,720);ctx.fillStyle='rgba(17,29,45,.9)';ctx.fillRect(0,620,920,58);ctx.fillStyle='#e73d36';ctx.fillRect(20,633,160,30);ctx.fillStyle='#fff';ctx.font='bold 15px DM Sans, sans-serif';ctx.fillText(category.value.toUpperCase(),31,653);ctx.font='bold 26px DM Sans, sans-serif';ctx.fillText(headline.value||'Your headline',202,656);if(document.querySelector('#logoToggle').checked){ctx.fillStyle='#e73d36';ctx.fillRect(24,24,42,42);ctx.fillStyle='#fff';ctx.font='bold 27px Georgia';ctx.fillText('A',38,54);ctx.font='bold 18px DM Sans, sans-serif';ctx.fillText('AAJ TAK ABHI TAK',80,52)}if(document.querySelector('#tickerToggle').checked){ctx.fillStyle='#e73d36';ctx.fillRect(0,678,1280,42);ctx.fillStyle='#fff';ctx.font='16px DM Sans, sans-serif';ctx.fillText('LATEST: Stay updated with Aaj Tak Abhi Tak News • Trusted news, every hour',24,704)}requestAnimationFrame(draw)};
  video.currentTime=0;recorder.start(1000);video.onended=()=>recorder.stop();await video.play();draw();
}
function showToast(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}
